### ISSUE TITLE
Shared artifacts for twirl-api ?

### ISSUE THREAD

**Issue by tomdz** [spray/twirl#8]
I've created a [maven plugin for twirl](https://github.com/tomdz/twirl-maven-plugin) for which I also need the twirl api as a compile and runtime dependency (for the generated code). The api code is at https://github.com/tomdz/twirl-api. I was wondering if you guys would be open to publishing the twirl api code (and maybe the compiler stuff) as separate artifacts to sbt & maven repos under the spray namespace ?

**Comment by cimbul** [comment]
I would also be very interested in any sort of Maven artifact for twirl-compiler. We're using the twirl-api artifact from the http://repo.spray.io/ repository, so that's not a problem (although it would be great to see this in Maven Central), and @tomdz's maven-scala-plugin works well for compiling the files before packaging. Since we want to support dynamic recompilation during development, though, we could really use a twirl-compiler artifact.

**Comment by jrudolph** [comment]
Since a while we are publishing twirl artifacts to the [sbt plugin repo](http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.spray/). However, this is a ivy style repo, so you can't use it from maven.

I think it would be perfectly possible to publish the same artifacts to the spray.io repo in maven style as well so that you can use them from maven as well.

**Comment by jrudolph** [comment]
Can you try with the new twirl 0.6.2 version? It should now be also published to repo.spray.io.

**Comment by cimbul** [comment]
Thanks! I can build my Maven project with the twirl-compiler artifact now.

Alas, I'm tied to Scala 2.10, and I see that there are several API changes in scala-compiler that mean `TwirlCompiler.scala` won't build against 2.10. Nothing you can do about that, since it's an upstream issue.

**Comment by jrudolph** [comment]
Yeah, I looked briefly into that as well this morning. The latest version of play seems to come with a 2.10 compatible compiler. However, because it seems they shuffled files around there's quite a bit of merging effort I have currently no time for. When I have a bit of free time for this I will try an update.
